services:
  vbc_liveqa:
    image: ghcr.io/rotundwizard/live_q-a:latest
    ports:
      - "3000:3000"
    volumes:
      - liveqa_data:/app/database
    environment:
      - MODERATOR_PASSWORD=mod123

volumes:
  liveqa_data:
